spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:47.97.57.227}:${DB_PORT:5432}/mty_land
    #127.0.0.1
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Mty233530}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        # 开放所有端点，生产环境不建议这么做
#        include: "*"


logging:
  level:
    org.springframework.security: debug
springfox:
  documentation:
    enabled: true
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true
