server:
  port: 9898

spring:
  profiles:
    active: dev

jwt:
  secret: mGjAl43hDy9VB247Z5AojYx2L3c7XG95CQoX6kZJ5WlVoIKA5Ri9O03mdobKnfqg

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springfox:
  documentation:
    enabled: false
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true