spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/mty_land
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

springfox:
  documentation:
    enabled: false
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true